version: '3.8'

services:
  # フロントエンド（React） - 環境3
  frontend-dev3:
    build:
      context: ../frontend
      dockerfile: Dockerfile.dev
    container_name: skillsheet-frontend-dev3
    ports:
      - "3002:3000"  # ホスト3002番ポートを使用
    volumes:
      - ../frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8002/api/v1
      - VITE_WS_URL=ws://localhost:8002
    depends_on:
      - backend-dev3
    networks:
      - skillsheet-network-dev3

  # バックエンド（Node.js） - 環境3
  backend-dev3:
    build:
      context: ../backend
      dockerfile: Dockerfile.dev
    container_name: skillsheet-backend-dev3
    ports:
      - "8002:8000"  # ホスト8002番ポートを使用
      - "9231:9229"   # デバッガー用（別ポート）
    volumes:
      - ../backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://skillsheet:password@postgres-dev3:5432/skillsheet_dev3
      - REDIS_URL=redis://redis-dev3:6379
      - ELASTICSEARCH_URL=http://elasticsearch-dev3:9200
      - JWT_SECRET=dev3-jwt-secret-change-in-production
      - JWT_EXPIRES_IN=7d
      - CORS_ORIGIN=http://localhost:3002
      - LOG_LEVEL=debug
      - PORT=8000
    depends_on:
      - postgres-dev3
      - redis-dev3
      - elasticsearch-dev3
    networks:
      - skillsheet-network-dev3

  # PostgreSQL - 環境3
  postgres-dev3:
    image: postgres:15-alpine
    container_name: skillsheet-postgres-dev3
    ports:
      - "5434:5432"  # ホスト5434番ポートを使用
    environment:
      - POSTGRES_USER=skillsheet
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=skillsheet_dev3
    volumes:
      - postgres_data_dev3:/var/lib/postgresql/data
    networks:
      - skillsheet-network-dev3
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U skillsheet"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis - 環境3
  redis-dev3:
    image: redis:7-alpine
    container_name: skillsheet-redis-dev3
    ports:
      - "6381:6379"  # ホスト6381番ポートを使用
    volumes:
      - redis_data_dev3:/data
    networks:
      - skillsheet-network-dev3
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Elasticsearch - 環境3
  elasticsearch-dev3:
    image: elasticsearch:8.11.0
    container_name: skillsheet-elasticsearch-dev3
    ports:
      - "9202:9200"  # ホスト9202番ポートを使用
      - "9302:9300"  # ホスト9302番ポートを使用
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - es_data_dev3:/usr/share/elasticsearch/data
    networks:
      - skillsheet-network-dev3
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  skillsheet-network-dev3:
    driver: bridge

volumes:
  postgres_data_dev3:
  redis_data_dev3:
  es_data_dev3: